parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 11
    matrix:
      py27_np15:
        PYTHON: '2.7'
        NUMPY: '1.15' 
        CONDA_ENV: 'travisci'
      py37_np15:
        PYTHON: '3.7'
        NUMPY: '1.15' 
        CONDA_ENV: 'travisci'

  steps:
    - script: |
        if [ "$(uname)" == "Linux" ]; then sudo apt-get install -y libc6-dev-i386; fi
        echo "Installing Miniconda"
        buildscripts/incremental/install_miniconda.sh
        export PATH=$HOME/miniconda3/bin:$PATH
        echo "Setting up Conda environment"
        buildscripts/incremental/setup_conda_environment.sh
      displayName: 'Before Install'

    - script: |
        export PATH=$HOME/miniconda3/bin:$PATH
        buildscripts/incremental/build.sh
      displayName: 'Build'

    - script: |
        export PATH=$HOME/miniconda3/bin:$PATH
        buildscripts/incremental/test.sh
      displayName: 'Test'
